Web/CyclingZone.Web/Controllers/FHomeController.cs
namespace CyclingZone.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using CyclingZone.Services.Data.Forum;
    using CyclingZone.Web.ViewModels.ForumHome;
    using Microsoft.AspNetCore.Mvc;

    public class FHomeController : BaseController
    {
        private readonly IForumCategoriesService forumCategories;

        public ForumHomeController(IForumCategoriesService forumCategories)
        {
            this.forumCategories = forumCategories;
        }

        public IActionResult Index()
        {
            var categories = this.forumCategories.GetAll<IndexForumCategoryViewModel>();

            return this.View(categories);
        }
    }
}

Web/CyclingZone.Web/Controllers/SubcategoriesController.cs
namespace CyclingZone.Web.Controllers
{
    using System.Linq;

    using CyclingZone.Services.Data;
    using CyclingZone.Web.ViewModels.Articles;
    using CyclingZone.Web.ViewModels.Subcategories;
    using Microsoft.AspNetCore.Mvc;

    public class SubcategoriesController : Controller
    {
        private readonly ISubcategoriesService subcategoriesService;
        private readonly IArticleService articleService;

        public SubcategoriesController(
            ISubcategoriesService subcategoriesService,
            IArticleService articleService)
        {
            this.subcategoriesService = subcategoriesService;
            this.articleService = articleService;
        }

        // GET: Subcategories/ Index
        public IActionResult Index(int articleId, int subcategoryId)
        {
            var articles = this.articleService
                   .GetBySubcategoryId<ArticleInSubcategoryViewModel>(articleId, subcategoryId);

            var viewModel = new IndexSubcategoryViewModel
            {
                Articles = articles,
            };

            return this.View(viewModel);
        }

        public IActionResult ByName(string name)
        {
            var articles = this.articleService.GetAll<ArticleInSubcategoryViewModel>(name);

            var viewModel = new IndexSubcategoryViewModel
            {
                Articles = articles,
            };

            return this.View(viewModel);
        }
    }
}

Web/CyclingZone.Web/Views/Shared/_ForumLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Power - Our Forum</title>

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="~/css/forum.min.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Cycling Zone </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="index.html">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="about.html">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="post.html">Sample Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('@Url.Content("~/images/forum.jpg")')">
        <div class="overlay"></div>
        <ul class="list-group float-right m-5 bg-transparent text-light">
            <li class="list-group-item bg-transparent">
                <img src="~/images/Forum/cyclocross.png" width="25" height="25" />&nbsp;&nbsp; A simple prima
            </li>
        </ul>
        <div class="container">
            <div class="row">

                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Clean Power</h1>

                        <span class="subheading">A Forum for Cyclist</span>
                    </div>
                </div>
            </div>

        </div>
    </header>

    <!-- Main Content -->
    <main>
        @this.RenderBody();
    </main>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 24, 2019
                    </p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                        </h2>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 18, 2019
                    </p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#">Start Bootstrap</a>
                        on August 24, 2019
                    </p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
                        </h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#">Start Bootstrap</a>
                        on July 8, 2019
                    </p>
                </div>
                <hr>
                <!-- Pager -->
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="~/js/forum.min.js"></script>

</body>

</html>

Web/CyclingZone.Web/Views/Shared/_Layout.cshtml
@using CyclingZone.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="collapse navbar-collapse" id="main_nav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="Home"
                       asp-action="Index">
                        @GlobalConstants.SystemName
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">  News  </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="Racing" class="dropdown-item"> Racing </a></li>
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="General news" class="dropdown-item"> General news</a></li>
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="Product news" class="dropdown-item"> Product news </a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">  Reviews  </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="Product news" class="dropdown-item"> Bike Reviews </a></li>
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="Bike Components" class="dropdown-item"> Bike Components </a></li>
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="Bike Accessories" class="dropdown-item"> Bike Accessories </a></li>
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="Clothing" class="dropdown-item"> Clothing </a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">  Fitness  </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="Bike Fit" class="dropdown-item"> Bike Fit</a></li>
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="Nutrition" class="dropdown-item"> Nutrition </a></li>
                        <li><a asp-controller="Subcategories" asp-action="ByName" asp-route-name="Training" class="dropdown-item"> Training </a></li>
                    </ul>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" asp-area="" asp-controller="FHome"
                       asp-action="Index">
                        @GlobalConstants.SystemName - Forum
                    </a>
                </li>
            </ul>
    </div> <!-- navbar-collapse.// -->

    <div>
        <partial name="_LoginPartial" />
    </div>
</nav>


<main>
    @this.RenderBody()
</main>
<div id="footer">
    <ul id="connect">
        <li>
            <a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook" title="Facebook"></a>
        </li>
        <li>
            <a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter" title="Twitter"></a>
        </li>
        <li>
            <a href="http://freewebsitetemplates.com/go/youtube/" target="_blank" class="vimeo" title="Vimeo"></a>
        </li>
        <li>
            <a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus" title="Google+"></a>
        </li>
    </ul>
    <div id="footnote">
        <ul>
            <li class="active">
                <a href="index.html">Home</a>
            </li>
            <li>
                <a href="about.html">About</a>
            </li>
            <li>
                <a href="blog.html">Blog</a>
            </li>
            <li>
                <a href="index.html">Gallery</a>
            </li>
        </ul>
        <span>&copy; Copyright &copy; 2020. Cycling Zone all rights reserved.</span>
    </div>
</div>

<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
<script src="~/js/site.min.js" asp-append-version="true"></script>
@await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>